version: '3.8'

services:
  swarm_sim:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    profiles:
      - batch
      - gui
    container_name: swarm_sim_container
    user: swarm
    stdin_open: true
    tty: true
    volumes:
      - ../src:/home/swarm/ws/src
      - ../scripts:/home/swarm/ws/scripts
      - swarm_storage:/home/swarm/sim_storage
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - PYTHONUNBUFFERED=1
      - AMENT_PREFIX_PATH=/home/swarm/ws/install:/opt/ros/humble   # <-- добавлено
    network_mode: host
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]

volumes:
  swarm_storage:
    driver: local